name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Change to 'master' if using master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/what-are-they-asking
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart what-are-they-asking
            sudo systemctl restart nginx
